# path (from the repository root) to sample sheet (TSV format, columns: sample, condition, ...)
samples: configuration/samples.tsv


# path (from the repository root) to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: configuration/units.tsv


# path (from the repository root) to cluster configuration. Parameters for submitting jobs to cluster via qsub
cluster: configuration/cluster.json


# Prefix to temporary
# Some files -such as fastq- occupy a lot of space. To avoid space problems during the processing of the pipelines
# we can use the temporary scratch of hpcnfs or the scratch directory of each node.
# Just write the prefix-path where you want to put those files, or write '.' to have them in the workdir.
# By now just fastq files will be located in this folder
# IMPORTANT: if you have running multiple snakemake pipelines with the same tmp folder all the fastq files will be located togeter. Care with the sample names to not be repeated.
tmp: /hpcnfs/scratch/temporary/.snakemake_am_rna


# perform trimming: false or true
# if true go to params (at the end)
# to set desired trimming parameters
trimming: false

# perform lfcshrink: FALSE or TRUE
# Set in capital letters since it will be read by R
# if true it will correct log2fc's using
# the apeglm method from DESeq2
lfcShrink: TRUE

# Set seed for downsampling
seed: 1234


ref:
  # Select the genome of the organism, needed to perform GO analyses. Supported: mouse, human.
  genome: "human"
  # the STAR index
  index: /hpcnfs/data/DP/STAR_INDEXES/v2.7.5a/hg38
  # gtf file with transcripts
  annotation: /hpcnfs/data/DP/STAR_INDEXES/v2.7.5a/hg38/gencode.vM21.annotation.gtf
  # This will be used to add different annotations to the DEGs table.
  # i.e: ensembl, entrez, ucsc... 
  geneInfo: 
    # path to geneInfo.tab file from STAR
    # leave it blank if there's no file or you don' want to perform this
    file: /hpcnfs/data/DP/STAR_INDEXES/v2.7.5a/hg38/geneInfo.tab
    # Define the position of the column used for the annotation and the column to add.
    # So, if we used geneSymbol as annotation (2nd column) and we want ENSEMBL (first)
    # Write 2 in used and 1 in toAdd
    column_used: 2
    column_toAdd: 1
    # Name of the annotation to add (ENSEMBL, SYMBOL, ENTREZID...)
    name_annotation: "ENSEMBL"


pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition
  # Number of top variable genes to show in PCA. Default is 500
  ntop: 500
    

diffexp:
  # samples to ignore. Write the name of the sample
  exclude: 
  # Filter thresholds to call differentially expressed genes
  fpkm: 
    - 0
  pvalue: 
    - 0.05
  log2fc: 
    - 1
    - 1.5
    - 2
    - 2.5
  # contrasts for the deseq2 results method
  contrasts:
    CTR_T-vs-CTR_NT:
      - CTR_T
      - CTR_NT
    P6KO_NT-vs-CTR_NT:
      - P6KO_NT
      - CTR_NT
    P6KO_T-vs-CTR_NT:
      - P6KO_T
      - CTR_NT

      
enrichments:
  # Perform or not enrichment analysis. True or False.
  do: True
  # Use background genes as universe in enrichment analyses. This SHOULD be
  # always used as it will give the most correct p-values. However, to be able to
  # still reproduce the results of the previous version of the pipeline we'll keep
  # this option. In the future this will be mandatory and the option will be removed.
  # set TRUE or FALSE in capital letters (it will be read by R).
  set_universe: TRUE
  # Adjusted p-value and q-value thresholds for enrichment analysis with 
  # clusterProfiler
  pval: 0.05
  qval: 0.1


# Parameters for some of the programs used in the pipeline
params:
  # Memory used by every core of samtools (GB). Be careful that
  # memory x threads is not bigger than the amount of memory assigned to align rule
  samtools_mem: 3
  star: "--outSAMattributes Standard \
        --outFilterMultimapNmax 1 \
        --readFilesCommand zcat"
  # By now the column used by featureCounts MUST contain the SYMBOL annotation since it's the one
  # used to transform gene names to ENTREZID for the enrichment analysis
  featureCounts: "-s 0 -t exon -g gene_name"
  # In case trimming is set to true, define trimmining parameters
  fastp-se: "--stdin -t 1 -A -Q -L"
  fastp-pe: "-t 1 -A -Q -L"
